language: node_js

env:
  - NODE_ENV=test

node_js:
  - "0.10"
  - "0.11"

before_script:
  - sudo apt-get install -qq build-essential libssl-dev libev-dev
  - wget http://www.haproxy.org/download/1.5/src/haproxy-1.5.1.tar.gz
  - tar xzvf haproxy-1.5.1.tar.gz
  - cd haproxy-1.5.1
  - make TARGET=linux26 USE_OPENSSL=1
  - sudo make install
  - cd ..

notifications:
  irc: "irc.freenode.org#observing"
  on_success: change
  on_failure: change
